### ISSUE TITLE
Digitial Ocean v1 provisioning will stop working November 15th, 2015

### ISSUE THREAD

**Issue by hh** [chef/chef-provisioning-fog#119]
Fog currently uses the [Digital Ocean v1 API](https://github.com/fog/fog/blob/master/lib/fog/digitalocean/examples/getting_started.md#getting-started-the-compute-service) but it will be turned off on [November 1st, 2015](https://developers.digitalocean.com/documentation/changelog/api-v1/sunsetting-api-v1/)

There is [fog fork/branch](https://github.com/phillbaker/fog/tree/feature/digitalocean-v2/) with last commit in January  from @phillbaker

@bryanl from Digital Ocean [mentioned in January](https://github.com/fog/fog/issues/3419#issuecomment-110425085 ) that they were looking to release fog-digitalocean but I haven't seen any public notices to that effect

There is a Bounty Source for $200 so far, with  $100 coming from someone at Digital Ocean....

**Comment by seanhandley** [comment]
Nice one @hh 

Is this something you'd like to get merged into master @phillbaker ? At a glance, the branch looks decent (though I'm not personally very familiar with the DO API itself).

**Comment by hh** [comment]
If we (as a community, or any company who needs to make it a priority) have any funds anywhere to allocate to this, I'd be willing to pick it up if we don't hear from @phillbaker
My focus is currently elsewhere, as I have to pay rent. ;)

**Comment by hh** [comment]
We could also write a chef-provisioning-digitalocean using https://github.com/digitalocean/droplet_kit might

**Comment by jjasghar** [comment]
:-O so yeah we need to get that updated....is there a fix on the fog.io side? It looks like they have removed DO completely?  Thoughts?

**Comment by bryanl** [comment]
I pushed a bunch of updates to fog to add support for our v2 compute last week. It'll eventually make it into a release, but it is in master. I didn't use droplet_kit because I didn't want to introduce any more dependencies to fog. Let me know if I can be of any assistance.

**Comment by jjasghar** [comment]
:metal: that's awesome @bryanl . I'll take a look at the commits and put my .02 in where relivant. If we're good I'm betting i can convince @tyler-ball to get a release sooner then later.

**Comment by hh** [comment]
:metal: :hand:  woohoo!

**Comment by hh** [comment]
:metal: :hand: woohoo!

**Comment by jjasghar** [comment]
@tyler-ball Sounds like we need a release here :metal:

**Comment by tyler-ball** [comment]
@jjasghar ping me when you have time and I'll show you how to get a release together!  Its mostly captured in https://github.com/chef/chef-provisioning-aws/blob/master/CONTRIBUTING.md#release-process but we need to add how to update the CHANGELOG and move those instructions into the base chef-provisioning project

**Comment by hh** [comment]
https://github.com/fog/fog/tree/v1.35.0 is released and includes Digital Ocean API V2 support.

**Comment by jjasghar** [comment]
I pushed out a new release of `chef-provisioning-fog` with no version constraint of `fog`. @hh does that resolve this issue?

If so, can you update the docs with an example of using the V2 for DO?

**Comment by hh** [comment]
I think it's going to be more complex than that. There are different keys etc and params to pass to the fog driver.

**Comment by hh** [comment]
https://github.com/fog/fog/blob/master/lib/fog/digitalocean/examples/getting_started.md still shows doc for v1

**Comment by hh** [comment]
Looks like we need to update to use https://github.com/fog/fog/blob/master/lib/fog/digitalocean/compute_v2.rb

**Comment by hh** [comment]
The new driver_opitons are basically :digitalocean_token

https://github.com/fog/fog/blob/master/lib/fog/digitalocean/compute_v2.rb#L64

```ruby
def initialize(options={})
  @digitalocean_token = options[:digitalocean_token]
end
```

**Comment by hh** [comment]
Looks like we have an entirely new DigitalOceanV2 class:

https://github.com/fog/fog/blob/v1.35.0/lib/fog/digitalocean/compute_v2.rb#L5

```ruby
module Fog
  module Compute
    class DigitalOceanV2 < Fog::Service
      requires :digitalocean_token
```

**Comment by hh** [comment]
#139 doesn't work yet, but it's slowly getting there. I can't work on this much at the moment, but I gave it a go tonight.

**Comment by hh** [comment]
#139 currently is mismatching on the _id versus _name etc on the bootstrap_options. Should be pretty straightforward to clean up.

**Comment by hh** [comment]
#139  now contains a working spike:

```ruby
source 'https://rubygems.org'
gem 'chef-provisioning'
gem 'chef-provisioning-fog', path: '../chef-provisioning-fog'
gem 'knife-digital_ocean'
gem 'fog', '=1.35.0'
```

```
# . .env bundle exec chef-client -z prov.rb || cat .chef/local-mode-cache/cache/chef-stacktrace.out
Chef::Log.info ENV['DOTOKEN']
with_driver 'fog:DigitalOcean', compute_options: {
                 digitalocean_token: ENV['DOTOKEN']
#                 digitalocean_api_key: 'DEPRECATED',
#                 digitalocean_client_id: 'DEPRECATED',
               }
# Adding compute_options here seems broken ^^^^
# so make sure and add driver_options to knife.rb

# put this in knife.rb
#knife[:digital_ocean_access_token] = ENV['DOTOKEN']
#driver_options compute_options: {digitalocean_token: ENV['DOTOKEN']}

with_machine_options convergence_options: {
                       chef_version: '12.4.3',
                       package_cache_path: '.chef/package_cache'
                     },
                     bootstrap_options: {
                       # Full list of DO Compute Options:
                       # https://github.com/fog/fog/blob/master/lib/fog/digitalocean/models/compute_v2/server.rb#L8

                       # name memory vcpus disk locked created_at status
                       # backup_ids snapshot_ids features region image
                       # size size_slug networks kernel
                       # next_backup_window private_networking backups
                       # ipv6 ssh_keys
                       
                       image_distribution: 'Ubuntu',
                       image_name: '14.04 x64',
                       region_name: 'New York 3',
                       flavor_name: '2GB',
                       private_networking: true,
                       key_name: 'iido5', # to create/use something
                       # other than .chef/keys/chef_default
                       # key_path: '/somewhereelse/if/you/want.key
                       tags: {
                         'ii' => 'lovesyou'
                       },
                     },
                     # just in case you create large instances and it takes a while
                     create_timeout: 600,
                     start_timeout: 600,
                     ssh_timeout: 600

with_chef_server 'https://api.chef.io/organizations/ii',
                 :client_name => Chef::Config[:node_name],
                 :signing_key_filename => Chef::Config[:client_key]

machine 'do.ii.delivery'
```

**Comment by hh** [comment]
Now for #140 so we can machine_image on do!
